version: "3.9"
services:
  scdefault:
    image: thoothuvan_buildapi:1.0
    restart: always
    ports:
      - '7003:8080'
    environment:
      module: "sc"
      smscid: "default"      
    networks:
      - thuthoovannw
networks:
  thuthoovannw:
    external: true        
 
