version: "3.9"
services:
  hapi:
    image: thoothuvan_buildapi:1.0
    restart: always
    ports:
      - '7002:8080'
    environment:
      module: "hapi"      
    networks:
      - thuthoovannw
networks:
  thuthoovannw:
    external: true        
 
