

# Spring MVC actuator endpoints available via /admin/info, /admin/health, ...
server.servlet-path: /sms-api/
management.context-path: /admin

info:
  app:
    name: kaloori
  build:
    version: V1

security:
  key: thamizh@amizh

spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?stringtype=unspecified&currentSchema=public&createDatabaseIfNotExist=true
    platform: postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    